// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SchoolApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "e4658f33-0b00-4932-b152-21bf610454f5",
                            FirstName = "Tom",
                            LastName = "Day",
                            School = "Physics"
                        },
                        new
                        {
                            StudentId = "d420cc6c-684c-4184-994d-f9df2f37b298",
                            FirstName = "Ann",
                            LastName = "Fox",
                            School = "Geology"
                        },
                        new
                        {
                            StudentId = "4858ee46-e370-4167-8054-4ebcbb118541",
                            FirstName = "Art",
                            LastName = "Ash",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "fc23e11c-1629-4ebe-915e-0bab9162c52b",
                            FirstName = "Mia",
                            LastName = "Hay",
                            School = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
